name: Latest tumblr activity
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from Tumblr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: caominhdev/blog-post-workflow@v1
        with:
          comment_tag_name: "TUMBLR"
          feed_list: "https://gaixinhchonloc.com/rss/"
          template: "<tr><td>$pubDate</td><td>$description</td></tr>"
