name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: caominhdev/blog-post-workflow@master
        with:
          feed_names: Tumblr
          feed_list: "https://gaixinhchonloc.com/rss/"
          max_post_count: "10"
          date_format: "mmm d, yyyy"
          custom_tags: "link/link:linkImage/"
          template: '<img width="140px" src="$linkImage">'
          committer_email: "caoquocminhktktbd@gmail.com"
